- C/services/dispatcher/controlrequest.cpp
- C/services/dispatcher/dispatcher_api.cpp
- C/services/dispatcher/dispatcher_service.cpp
- C/services/dispatcher/include/automation.h
- C/services/dispatcher/include/controlrequest.h
- C/services/dispatcher/include/dispatcher_api.h
- C/services/dispatcher/include/dispatcher_service.h
- C/services/dispatcher/include/kvlist.h
- C/services/dispatcher/kvlist.cpp
Check in to allow other components to use progress to date
> FOGL-6066 Dispatcher API and Skeleton 

- C/services/dispatcher/controlrequest.cpp
> Fix log message

- C/services/dispatcher/automation.cpp
- C/services/dispatcher/controlrequest.cpp
- C/services/dispatcher/dispatcher_api.cpp
- C/services/dispatcher/dispatcher_service.cpp
- C/services/dispatcher/include/dispatcher_service.h
Reverts fledge-iot/fledge-service-dispatcher#8
> Revert "FOGL-5144: pass Dispatcher bearer token in service operation"

- C/services/dispatcher/automation.cpp
FOGL-6240: 'steps' property can be string or JSON
> FOGL-6240: 'steps' property can be string or JSON

- C/services/dispatcher/include/dispatcher_service.h
FOGL-5144: addition of isRunning() routine
> FOGL-5144: addition of isRunning() routine

- C/services/dispatcher/automation.cpp
> Fix passing of parameters

- C/services/dispatcher/dispatcher_service.cpp
- C/services/dispatcher/include/dispatcher_service.h
> Adding server config category

- C/services/dispatcher/dispatcher_service.cpp
> Fix enable/disable global control

- C/services/dispatcher/dispatcher_service.cpp
- C/services/dispatcher/include/dispatcher_service.h
> FOGL-5181 Add --dryrun option

- C/services/dispatcher/dispatcher_service.cpp
Signed-off-by: ashish-jabble <ashish@dianomic.com>
> FOGL-6690 Fixes made for no matching function call in createSecurityCategories

- C/services/dispatcher/dispatcher_service.cpp
> FOGL-6611: set service type

- C/services/dispatcher/dispatcher_service.cpp
- C/services/dispatcher/include/dispatcher_service.h
> FOGL-6854 Support restart fopr when bearer token can not be refreshed

- C/services/dispatcher/dispatcher.cpp
> FOGL-6835 Reinstate check for --dryrun flag

- C/services/dispatcher/controlrequest.cpp
> FOGL-6794 Fix plugin type string

- C/services/dispatcher/kvlist.cpp
> FOGL-7009: escape quotes in write values and operation parameters

- C/services/dispatcher/dispatcher_service.cpp
> FOGL-7039 improve control operation failure diagnostics

- C/services/dispatcher/dispatcher_service.cpp
Requires FOGL-7421 before merging
> FOGL-7424 Add singleton AuditLogger

- C/services/dispatcher/dispatcher_api.cpp
FOGL.8343: skip service authentication for table operations
> FOGL.8343: skip service authentication for table operations

- C/services/dispatcher/include/pipeline_manager.h
- C/services/dispatcher/pipeline_manager.cpp
FOGL-8343: retrieve cpid from storage after pipeline creation
getFromJSONWhere now deals with long values
> FOGL-8343: retrieve cpid from storage after pipeline creation

- C/services/dispatcher/pipeline_manager.cpp
- Fixed JSON parsing for cpid.
> FOGL-8523: Control Pipeline filters not getting added on pipeline creation

- C/services/dispatcher/controlpipeline.cpp
- C/services/dispatcher/include/pipeline_execution.h
- C/services/dispatcher/pipeline_execution.cpp
This PR has fix for FOGL-8794 as well
> FOGL-8648 : Implemented removeFilter and reorder method
